services:
  postgres:
    build:
      context: ./db
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: swift_db
    networks:
      - my-network
    ports:
      - "5432:5432"
  app:
    build: 
      context: ./app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
